# Generated by Django 3.2.8 on 2021-10-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgserver', '0002_alter_message_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg',
            field=models.TextField(),
        ),
    ]
