# Generated by Django 3.2.8 on 2021-10-27 21:03

from django.db import migrations, models
import msgserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('msgserver', '0005_alter_message_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.AlterField(
            model_name='message',
            name='key',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, validators=[msgserver.models.validate_key_alphanum, msgserver.models.validate_key_length, msgserver.models.validate_key_unique]),
        ),
    ]
